config/routes.rb
Rails.application.routes.draw do
  resources :embeddings, only: [:create]
  resources :chats, only: [:create]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "dashboard#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/embedding.rb
class Embedding < ApplicationRecord
  has_neighbors :embedding
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def create
    client = Ollama.new(
      credentials: { address: 'http://localhost:11434' },
      options: { server_sent_events: true }
    )

    embeddings_result = client.embeddings(
      { model: 'llama3.2',
        prompt: params[:prompt] }
    )
    
    vector = embeddings_result[0]["embedding"]

    neighbors = Embedding.nearest_neighbors(:embedding, vector, distance: "euclidean").first(5)
    context = neighbors.pluck(:prompt).join(", ")

    prompt = "prompt: #{params[:prompt]} context: #{context}"
    @chat_result = client.generate(
      { model: 'llama3.2',
        prompt: prompt,
        stream: false }
    )
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def show
  end
end

app/controllers/embeddings_controller.rb
class EmbeddingsController < ApplicationController
  def create
    client = Ollama.new(
      credentials: { address: 'http://localhost:11434' },
      options: { server_sent_events: true }
    )

    result = client.embeddings(
      { model: 'llama3.2',
        prompt: params[:prompt] }
    )
    
    @embedding = Embedding.create(embedding: result[0]["embedding"], prompt: params[:prompt])

    if @embedding.save
      @text = "Your model was updated with the info :)"
    else
      @text = @embedding.errors.full_messages.join(", ")
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/chats/create.turbo_stream.erb
<%= turbo_stream.update("chat-response", partial: "dashboard/chat_message", 
      locals: { text: @chat_result[0]["response"]}) %>

<%= turbo_stream.update("chat-form", partial: "dashboard/chat_form") %>

app/views/dashboard/_alert.html.erb
<div class="px-3 py-4 rounded-lg bg-gray-100 border-2 border-green-500 mr-auto absolute top-8 left-8" id="alert-element"> 
  <%= text %>
</div>

<%= javascript_tag do %>
  setTimeout(() => {
    document.querySelector("#alert-element").remove()
  }, 2500)
<% end %>

app/views/dashboard/_chat_form.html.erb
<%= form_with url: chats_path do |f| %>
  <div class="flex flex-col gap-2"> 
    <%= f.label :prompt, class: "text-lg text-indigo-50" %>
    <%= f.text_area :prompt, class: "h-40 p-2" %>
  </div>

  <%= f.submit "Chat with model", class: "px-3 py-2 rounded-full bg-blue-500 text-blue-50 cursor-pointer mt-4 hover:scale-105" %>
<% end %>

app/views/dashboard/_chat_message.html.erb
<div class="rounded-lg bg-gray-300 p-4 text-gray-900"> 
  <%= text %>
</div>

app/views/dashboard/_embeddings_form.html.erb
<%= form_with url: embeddings_path do |f| %>
  <div class="flex flex-col gap-2"> 
    <%= f.label :prompt, class: "text-lg text-indigo-50" %>
    <%= f.text_area :prompt, class: "h-40 p-2" %>
  </div>

  <%= f.submit "Train the model!", class: "px-3 py-2 rounded-full bg-blue-500 text-blue-50 cursor-pointer mt-4 hover:scale-105" %>
<% end %>

app/views/dashboard/show.html.erb
<div class="flex flex-col w-full min-h-[200vh] bg-gradient-to-br from-indigo-700 to-indigo-500 pt-36">
  <div id="alert"> 
  </div>
  <div class="max-w-7xl w-full mx-auto">
    <h1 class="text-5xl text-indigo-50"> Your Dashboard </h1>

    <div class="mt-8 bg-gray-600 p-4 min-h-[30vh]">
      <h2 class="text-3xl text-gray-100 flex items-center gap-4"> 
        <%= image_tag "toy-train.png", class: "w-12 object-cover" %>
        <span> Train the model </span> 
      </h2>
      <div id="embeddings-form">
        <%= render "embeddings_form" %>
      </div>
    </div>

    <div class="mt-8 bg-gray-600 p-4 min-h-[30vh]"> 
      <h2 class="text-3xl text-gray-100 flex items-center gap-4"> 
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-12">
          <path stroke-linecap="round" stroke-linejoin="round" d="M7.5 8.25h9m-9 3H12m-9.75 1.51c0 1.6 1.123 2.994 2.707 3.227 1.129.166 2.27.293 3.423.379.35.026.67.21.865.501L12 21l2.755-4.133a1.14 1.14 0 0 1 .865-.501 48.172 48.172 0 0 0 3.423-.379c1.584-.233 2.707-1.626 2.707-3.228V6.741c0-1.602-1.123-2.995-2.707-3.228A48.394 48.394 0 0 0 12 3c-2.392 0-4.744.175-7.043.513C3.373 3.746 2.25 5.14 2.25 6.741v6.018Z" />
        </svg>
        <span> Chat with model</span> 
      </h2>

      <div id="chat-form"> 
        <%= render "chat_form" %>
      </div>
    </div>

    <div id="chat-response" class="mt-4"> </div>
  </div>
</div>

app/views/embeddings/create.turbo_stream.erb
<%= turbo_stream.update("embeddings-form", partial: "dashboard/embeddings_form") %>
<%= turbo_stream.update("alert", partial: "dashboard/alert", 
    locals: { text: @text }) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Train Ai" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>